### PR TITLE
bundle only monaco-editor api

### PR DESCRIPTION
**Pull request by terryzfeng**
Clean up bundling so that Monaco-Vim only includes the core functionality of Monaco-Editor

### CODE REVIEW

**Comment by brijeshb42** [comment]
Could you remove `package-lock.json`?

**Comment by terryzfeng** [comment]
Removed!

**Comment by brijeshb42** [comment]
1 last comment, could you also remove all the changes in `yarn.lock` file as the core changes do not depend on that. After that, I'll merge and publish a new version.

**Comment by terryzfeng** [comment]
Thanks! Got it!

**Pull request merged**
